import type { Metadata } from "next"
import "./globals.css"
import LayoutMain from "@/components/layout/main"
import { Plus_Jakarta_Sans as PrimaryFont } from "next/font/google"
import ReduxProvider from "@/lib/store/index.store"

const primaryFont = PrimaryFont({
   subsets: ["latin"],
   variable: "--font-primary",
   weight: ["200", "300", "400", "500", "600", "700", "800"],
})

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={`${primaryFont.variable} font-primary antialiased`}>
            <ReduxProvider isMock={false}>
               <LayoutMain>{children}</LayoutMain>
            </ReduxProvider>
         </body>
      </html>
   )
}
