import type { Metadata } from "next"
import "./globals.css"
import LayoutMain from "@/components/layout/main"
import StoreMockProvider from "@/lib/store/index.mock"
import { Plus_Jakarta_Sans as PrimaryFont } from "next/font/google"

const primaryFont = PrimaryFont({
   subsets: ["latin"],
   variable: "--font-primary",
})

export const metadata: Metadata = {
   title: "Create Next App",
   description: "Generated by create next app",
}

export default function RootLayout({
   children,
}: Readonly<{
   children: React.ReactNode
}>) {
   return (
      <html lang="en">
         <body className={`${primaryFont.variable} font-primary antialiased`}>
            <StoreMockProvider>
               <LayoutMain>{children}</LayoutMain>
            </StoreMockProvider>
         </body>
      </html>
   )
}
